config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'lists#index'
  resources :lists, except: [:index] do
    resources :bookmarks, only: %i[create new]
    resources :reviews, only: %i[create new]
  end
  resources :bookmarks, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :comment, :rating, presence: true
  validates :rating, 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list), notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :find_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def edit
    
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list), notice: "list was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lists/1
  def update
    if @list.update(list_params)
      redirect_to root_path, notice: "list was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to root_path, notice: "list was successfully destroyed.", status: :see_other
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, "Créer un signet", class: "btn btn-primary" %>
  
<% end %>

app/views/bookmarks/new.html.erb
<h1 class = "mb-3 text-center">Ajouter un nouveau signet</h1>

<div class="container w-50">
  <%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_footer.html.erb
<footer class="footer mt-5">
    <div class="footer-container">
    <div class="footer-row">
      <div class="footer-col">
        <h4>Company</h4>
        <ul>
          <li><a href="#">about us</a></li>
          <li><a href="#">our services</a></li>
          <li><a href="#">privacy policy</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>get help</h4>
        <ul>
          <li><a href="#">FAQ</a></li>
          <li><a href="#"></a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Product</h4>
        <ul>
          <li><a href="#">Movies</a></li>
          <li><a href="#">Bookmark</a></li>
          <li><a href="#">Lists</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h4>Follow us</h4>
        <div class="social-links">
          <a href="https://www.facebook.com/profile.php?id=100091522343209"><i class="fab fa-facebook-f"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-linkedin-in"></i></a>
        </div>
      </div>
    </div>
    </div>
</footer>

app/views/lists/_form_edit.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.button :submit, "Editer la list!", class: "btn btn-primary" %>
  <%= link_to "retour", root_path, class: "btn btn-dark"  %>
<% end %>

app/views/lists/_form_new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.button :submit, "Créer la list!", class: "btn btn-primary" %>
  <%= link_to "retour", root_path, class: "btn btn-dark"  %>
<% end %>

app/views/lists/edit.html.erb
<h1 class = "text-center">Editer la list <%= @list.name %></h1>

<div class=" container w-50">
  <%= render "form_edit" %>
</div>

<%= render "footer" %>

app/views/lists/index.html.erb
<div class= "containe h-100 ">
  <h1 class= "text-center">My lists</h1>

  <%# affichage de la banner  %>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80);">
    <div class="container">
      <p class= "text-center text-white " >Save any kind of movie</p>
      <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Ajouter un list", new_list_path, class: "btn btn-secondary text-center"  %>
      </div>

    </div>
  </div>


  <%# affichage des lists  %>

  <div class="container mt-3">
    <div class= "cards">
      <% @lists.each do |list| %>
        <div>
          <%= link_to list_path(list) do  %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key, height: 300, crop: :fill %>)">
              <%= list.name %>
            </div>
          <% end %>
          <div class="d-flex edit justify-content-evenly">
              <%= link_to "Delete", list_path(list), data: {
                            turbo_method: :delete,
                            turbo_confirm: 'Oui vraiment? 🥲'
                          }, class: "text-danger"  %>
              <%= link_to "Edit", edit_list_path(list), class: "text-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# affichage du footer %>
<%= render "footer" %>

app/views/lists/new.html.erb
<div class="new_container">
  <h1 class="mb-5 text-center">Créer une nouvelle list</h1>

  <div class="container w-50">
    <%= render "form_new" %>
  </div>

</div>
<%= render "footer" %>


<% @reservations_received.each do |resa| %>
  <div class="card-product">
    <% if resa.cat.photos.attached? %>
      <%resa.cat.photos.first(1).each do |img| %>
        <%= cl_image_tag img.key, crop: :fill %>
      <% end %>
    <% else %>
      <img src="<%= resa.cat.images_url[0]%>" alt="">
    <% end %>
    <div class="card-product-infos">
      <div class="d-flex  ">
        <div class = "mx-3 " >
        <p class="text-start ">Name <%= resa.cat.name %></p>
        <p class=" text-start ">date_st <%= resa.start_date %></p>
        <p class=" text-start ">date_en <%= resa.end_date %></p>
        <p class=" text-start ">total <%= resa.total_price %> </p>
        <p class=" text-start ">Statut: <%= resa.statut_string %></p>
        </div>
        <% if resa.statut.nil? %>
        <div class= "  ">
          <p class =" margin-btn btn-grad-green"> <%= link_to 'Approuver', edit_user_registration_path %></p>
          <p class =" margin-btn btn-grad-red"> <%= link_to 'Refuser ', edit_user_registration_path %></p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/lists/show.html.erb
<%# nav barre  %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= cl_image_tag @list.photo.key, class: "rounded" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Créer une nouvelle list", new_list_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "My lists", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Ajouter un nouveau signet", new_list_bookmark_path(@list), class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>


<%# affichage de la banner  %>
<div class="banner position-relative" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, height: 300, crop: :fill %>);">
  <div class="container">
    <h2 class="text-center text-white">Vous êtes sur la list <strong><%= @list.name %></strong></h2>
  </div>
  <div class= "movies-count p-3 bg-warning text-white rounded">
    Movies: <%= @list.movies.count %>
  </div>
</div>



<br><br>

<div>
  <%= link_to "Ajouter un film à cette list", new_list_bookmark_path(@list), class: "btn btn-secondary"%>
</div>


<div class="container">
  <div class= "card-trip">
    <div class="cards">
      <%  @list.movies.each do|movie|%>
        <div class="card-trip">
          <img src="<%= movie.poster_url  %>",   />
          <div class="card-trip-infos">
            <div>
              <h2><%= movie.title %> : <span class="text-secondary"><%=  movie.rating %>/10 </span></h2>
              <p><%= movie.overview  %></p>
            </div>
          </div>
          <div class= "card-trip-infos d-flex">
            <% bookmark = Bookmark.find_by(movie: movie, list: @list) %>
            <h2 class="text-secondary">"<%= bookmark.comment %>...</h2>
            <h2 class="text-danger"><%= link_to "delete", bookmark_path(bookmark), data: {
                      turbo_method: :delete,
                      turbo_confirm: 'Oui vraiment? 🥲'
                    }, class: "text-danger"  %></h2>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%# affichage footer %>

<%= render "footer" %>